# 기본 사이트 정보
title: "La bohème"
subtitle: "by @haanss"
name: "영화와 음악은 계절을 따라 흘러갑니다."
description: "@haanss blog by Jekyll"

# URL 및 퍼머링크 설정
url: "https://test.la-bohe.me"
baseurl: ""

# 포스트 주소 형식 지정
permalink: /:title/
search: true

# GitHub Pages 원격 테마 설정
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "contrast"

# 플러그인 설정 (jekyll-paginate 제외 및 필수 플러그인 구성)
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-archives

# 네비게이션 및 페이지 기본 레이아웃 설정
defaults:
  # pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
      show_date: true
      date_format: "%Y-%m-%d"
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      show_date: true
      date_format: "%Y-%m-%d"
      comments: false
      share: true
      related: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-square-x-twitter"
      url: "https://twitter.com/la-boheme-host"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/la-boheme-host"
      rel: "me"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/haanss"

# 카테고리 및 태그 아카이브 설정
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/